version: 2.3.{build}
image: Visual Studio 2017 Preview
clone_folder: C:\Projects\Victoria
skip_commits:
  message: /Update/
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet build
artifacts:
- path: '**\*.nupkg'
  name: Victoria
deploy:
- provider: NuGet
  api_key:
    secure: 2ERjvGaKjBby9aE8IHGo0uBHqXuosD3em2isgwubNPD9Zwt1q+y1WOopXW2dmH6j
  artifact: Victoria
on_success:
- ps: Invoke-RestMethod https://raw.githubusercontent.com/Yucked/Krypts/master/VeyorHook.ps1 -o VeyorHook.ps1
- ps: ./VeyorHook.ps1 success $env:WEBHOOK_URL
on_failure:
- ps: Invoke-RestMethod https://raw.githubusercontent.com/Yucked/Krypts/master/VeyorHook.ps1 -o VeyorHook.ps1
- ps: ./VeyorHook.ps1 failure $env:WEBHOOK_URL
